source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

group :alpine_linux do
  # gem 'ffi', '= 1.9.14'
  # gem 'nokogiri', '= 1.8.1'
end

gem 'json'
gem 'sinatra'

# Adhearsion 3.0.0rc1
gem 'adhearsion', github: 'adhearsion/adhearsion'
gem 'matrioska', github: 'adhearsion/matrioska', branch: 'feature/adhearsion-3'

group :development do
  gem 'pry'
  gem 'pry-remote'

  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
  gem 'pry-byebug'
end

group :test do
  gem 'rspec'
  gem 'rspec-expectations'
end
